services:
  shopizer-user-service:
    container_name: shopizer-user-service
    image: thaidoan868/shopizer-user-service:latest
    #    build:
    #      context: .
    #      dockerfile: shopizer-user-service/Dockerfile

    environment:
      SPRING_PROFILES_ACTIVE: staging
      # update the following environment variable with your actual Keycloak client secret
      KEYCLOAK_USER_SERVICE_CLIENT_SECRET: ${KEYCLOAK_USER_SERVICE_CLIENT_SECRET}
      MINIO_ACCESS_ENDPOINT: ${MINIO_ACCESS_ENDPOINT}
      MANAGEMENT_HEALTH_MAIL_ENABLED: "false"

    ports:
      - "8082:8082"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9100/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


    restart: unless-stopped
    networks:
      - appnet