services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: shopizer
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks: [ appnet ]
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command:
      - start-dev
      - --http-port=8080
      - --http-management-port=9000
      - --hostname-strict=false
      - --proxy-headers=xforwarded
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/shopizer
      KC_DB_USERNAME: postgresadmin
      KC_DB_PASSWORD: adminpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8888:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "timeout 2 bash -lc 'cat < /dev/null > /dev/tcp/127.0.0.1/9000'" ]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [ appnet ]

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    ports:
      - "9000:9000"   # S3 API
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9000/minio/health/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    networks: [ appnet ]

  redpanda:
    image: redpandadata/redpanda:v25.3.4
    container_name: redpanda
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 1G
      --reserve-memory 0M
      --node-id 0
      --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://redpanda:9092
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9644/v1/status/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12

  #   Motoring


  jaeger: # traces
    image: jaegertracing/all-in-one:1.76.0
    container_name: jaeger
    ports:
      - "127.0.0.1:16686:16686" # UI
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:16686/ >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    networks: [ appnet ]

  prometheus: # metrics
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./infra/dev/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    depends_on:
      jaeger:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:9090/-/ready >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    networks: [ appnet ]

  # Logging
  fluent-bit:
    image: fluent/fluent-bit:3.1
    container_name: fluent-bit
    command: [ "-c", "/fluent-bit/etc/fluent-bit.conf" ]
    volumes:
      # Read Docker container logs (stdout/stderr)
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

      # Fluent Bit config
      - ./infra/dev/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./infra/dev/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - fluentbit_tail_data:/fluent-bit/tail-db
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    restart: unless-stopped
    networks: [ appnet ]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    networks: [ appnet ]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana

    environment:
      # Elasticsearch connection
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      # allow Kibana to safely store sensitive data inside Elasticsearch.
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "b0b8f4c6e8c24b8f9f3d3f7d9a1c2e3f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d"

      # Disable security for dev (REMOVE in prod)
      XPACK_SECURITY_ENABLED: "false"

      SERVER_NAME: kibana
      SERVER_HOST: 0.0.0.0

    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:5601/api/status" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    ports:
      - "127.0.0.1:5601:5601"
    restart: unless-stopped

    networks: [ appnet ]

  # Boostrap
  bootstrap:
    build:
      context: ./infra/dev/bootstrap
    environment:
      # Keycloak
      TF_VAR_KEYCLOAK_URL: http://keycloak:8080
      TF_VAR_KEYCLOAK_ADMIN_USERNAME: admin
      TF_VAR_KEYCLOAK_ADMIN_PASSWORD: adminpassword
      TF_VAR_BACKEND_CLIENT_SECRET: backendclientsecret
      TF_VAR_DEFAULT_ADMIN_USERNAME: admin
      TF_VAR_DEFAULT_ADMIN_PASSWORD: admin

      # MinIO
      TF_VAR_MINIO_ENDPOINT: http://minio:9000
      TF_VAR_MINIO_ROOT_USER: admin
      TF_VAR_MINIO_ROOT_PASSWORD: adminpassword

    depends_on:
      keycloak:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - terraform_data:/work/terraform
      - ./infra/dev/bootstrap/terraform/main.tf:/work/terraform/main.tf:ro
      - ./infra/dev/bootstrap/terraform/variables.tf:/work/terraform/variables.tf:ro

    working_dir: /work/terraform
    networks: [ appnet ]

  # Microservices
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: shopizer-api-gateway/Dockerfile

    image: shopizer/api-gateway:1.0.0

    environment:
      SPRING_PROFILES_ACTIVE: dev

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - appnet

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: shopizer-user-service/Dockerfile

    image: shopizer/user-service:1.0.0

    environment:
      SPRING_PROFILES_ACTIVE: dev

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy


    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:

volumes:
  postgres_data:
  minio_data:
  redpanda_data:
  es_data:
  prom_data:
  fluentbit_tail_data:
  terraform_data:

