[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Tag               docker.*
    Parser            docker
    DB                /fluent-bit/tail-db/tail.db
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  5


[OUTPUT]
    Name            es
    Match           docker.*
    Host            ${ES_HOST}
    Port            ${ES_PORT}
    Index           logs-docker
    Logstash_Format On
    Logstash_Prefix logs
    Suppress_Type_Name On
    Retry_Limit     False
