server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      javax:
        persistence:
          validation:
            mode: auto
  flyway:
    enabled: false
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/shopizer/protocol/openid-connect/certs
  jackson:
    default-property-inclusion: non_null

management:
  server:
    port: 9003
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always

# Documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  level:
    root: INFO
    vn.io.oldmoon.shopizer: TRACE
  pattern:
    level: "%5p"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] - %msg%n"

keycloak:
  server-url: http://localhost:8080
  realm: shopizer
  client-id: backend
  client-secret: backendclientsecret