spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI}
          default-label: ${GIT_CONFIG_LABEL:main}
          clone-on-start: ${GIT_CLONE_ON_START:true}
          search-paths:
            - ${GIT_SEARCH_PATH:config}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
